version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    govet:
      enable:
        - shadow
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - wrapperFunc
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/stretchr/testify"
              desc: "testify should only be used in tests"
          allow:
            - $gostd
            - github.com/maxjustus/bpuf

run:
  timeout: 5m